POST http://localhost:8810/api/payment
Content-Type: application/json

{
  "currency": "ETH",
  "amount": "0.01",
  "merchantId": 1
}

###
POST http://localhost:8810/api/payment
Content-Type: application/json

{
  "currency": "ETH",
  "amount": "0.01",
  "merchantId": 1,
  "callbackUrl": ""
}

###
POST http://localhost:8810/api/payment
Content-Type: application/json

{
  "currency": "ETH",
  "amount": "0.01",
  "merchantId": 1,
  "callbackUrl": "sds"
}

###
GET http://localhost:8810/api/payment/1
