server:
  port: 8810
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mariadb://localhost:3510/cryptogate
    username: cryptogate
    password: cryptogate
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.MariaDB106Dialect

    hibernate:
      ddl-auto: update
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: TRACE

refresh:
  etherscan:
    enabled: true
    cron: "*/2 * * * * *"