server:
  port: 8810

spring:
  datasource:
    url: jdbc:mariadb://localhost:3510/cryptogate
    username: cryptogate
    password: cryptogate
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    use_sql_comments: true
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect

    open-in-view: false

    hibernate:
      ddl-auto: update
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

refresh:
  etherscan:
    enabled: true
    cron: "*/2 * * * * *"